#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
# bspc config focused_border_color \#F9F9FB
bspc config focused_border_color \#222222
bspc config normal_border_color \#D2D8E0
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# Autostart
$HOME/.screenlayout/screen.sh &
picom &
compton --restore &
# feh /home/angel/wallpaper/nya.png &
nitrogen --restore &
lxappearance &
$HOME/.config/polybar/launch.sh &
